### DISCUSSION TITLE
Unable to Filter Metrics Using Resource Attributes - resource_attributes

### DISCUSSION THREAD

**Discussion by mskhan-devops** [open-telemetry/opentelemetry-cpp#1222] [Show and tell]
Hi Everyone,
As per the example on page [opentelemetry-collector-contrib/processor/filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#filter-processor), I am trying to configure ADOT Collector Pipeline for EKS cluster to publish metrics to CloudWatch Container Insights:
```
processors:
  filter/1:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - pod_cpu_.*
```
This works fine and I see filtered metrics against my apps in the Container Insights.

The problem is as soon as I add `resource_attributes` to the above configuration to filter out metrics against the specific app running in the EKS cluster, like below:

```
processors:
  filter/1:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - pod_cpu_.*
        resource_attributes:
          - Key: k8s.pod.name
            Value: myapp-pod-with-hash.*

```
**AWS ADOT Collector stops publishing any metrics to Container Insights. Can anyone please help with this?**

I am using this guide and sample config file:
[Cost savings by customizing metrics sent by Container Insights in Amazon EKS
](https://aws.amazon.com/blogs/containers/cost-savings-by-customizing-metrics-sent-by-container-insights-in-amazon-eks/
)
Sample config file:
[otel-container-insights-infra.yaml](https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-container-insights-infra.yaml
)

Thanks
